version: '3'
services:

  web:
    build: .
    container_name: book-api-springboot
    networks:
      -  bookapi-network
    ports:
      - "8487:8487"
    depends_on:
      db:
        condition: service_healthy
    command:  ["java","-jar","/app.jar"]
    env_file:
      - default.env

  db:
    image: postgres
    container_name: db
    networks:
      - bookapi-network
    restart: always
    ports:
      - "5154:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - default.env

networks:
  bookapi-network:
    driver: bridge