spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST_NAME}:${DB_PORT}/${DB_BANE}
    username: ${DB_APP_USER}
    password: ${DB_APP_USER_PWD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
